# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      proxiable|proxiableCollector:
        enabled: true
      proxiable|proxiableCombiner:
        enabled: true
builders:
  proxiable|proxiableCollector:
    import: 'package:proxiable/src/builder/builder.dart'
    builder_factories: ['proxiableCollector']
    build_extensions: { '.dart': ['.proxiable.json'] }
    runs_before: ['proxiable|proxiableCombiner']
    auto_apply: root_package
    build_to: cache
  proxiable|proxiableCombiner:
    import: 'package:proxiable/src/builder/builder.dart'
    builder_factories: ['proxiableCombiner']
    build_extensions: { '.dart': ['/generated/proxiable.dart'] }
    runs_before: ['reflectable']
    auto_apply: root_package
    build_to: source
