# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
targets:
  $default:
    builders:
      proxiable|proxiableCollector:
        enabled: true
        generate_for:
          exclude: ['lib/generated/**']
      proxiable|proxiableCombiner:
        enabled: true
        generate_for:
          exclude: ['lib/generated/**']
builders:
  proxiable|proxiableCollector:
    import: 'package:proxiable/src/builder/builder.dart'
    builder_factories: ['proxiableCollector']
    build_extensions: { '.dart': ['.proxiable_cache.part'] }
    runs_before: ['proxiable|proxiableCombiner']
    auto_apply: dependents
    build_to: cache
  proxiable|proxiableCombiner:
    import: 'package:proxiable/src/builder/builder.dart'
    builder_factories: ['proxiableCombiner']
    build_extensions: { '.dart': ['.proxiable.g.dart'] }
    runs_before: ['reflectable']
    auto_apply: dependents
    build_to: source
