name: proxiable
description: >
  Proxy provides static methods for creating dynamic proxy classes and instances,
  and it is also the superclass of all dynamic proxy classes created by those methods.
version: 0.3.0
homepage: https://github.com/copydog/proxiable
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  reflectable: any
  analyzer: any
  build: any
  source_gen: '>=0.8.0'
  build_config: '>=0.3.0'
  glob: any
  mustache: 1.1.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: any
