name: proxiable
description: >
  Proxy provides static methods for creating dynamic proxy classes and instances,
  and it is also the superclass of all dynamic proxy classes created by those methods.
version: 0.4.1+2
homepage: https://github.com/copydog/proxiable
author: Copydog <775150@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  reflectable: ^2.2.0
  build: ^1.2.0
  reflectable_annotation: ^1.0.0
  exporter: ^1.0.2
  matchable_builder: ^0.4.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.7.1
